import type { Meal, BMICategory } from '@/types';

const meals: Record<BMICategory, Meal[]> = {
  underweight: [
    {
      id: 'uw-b1',
      name: 'Banana Walnut Oatmeal',
      category: 'breakfast',
      calories: 520,
      protein: 18,
      carbs: 62,
      fat: 18,
      image: 'https://images.pexels.com/photos/566564/pexels-photo-566564.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['1 cup rolled oats', '1 banana', '30g walnuts', '2 tbsp honey', '300ml whole milk'],
      prepTime: 10,
    },
    {
      id: 'uw-l1',
      name: 'Chicken Avocado Rice Bowl',
      category: 'lunch',
      calories: 750,
      protein: 42,
      carbs: 78,
      fat: 28,
      image: 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['200g grilled chicken', '1 avocado', '1.5 cups white rice', 'Black beans', 'Salsa'],
      prepTime: 20,
    },
    {
      id: 'uw-d1',
      name: 'Salmon with Sweet Potato',
      category: 'dinner',
      calories: 680,
      protein: 38,
      carbs: 55,
      fat: 32,
      image: 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['220g salmon fillet', '1 large sweet potato', 'Olive oil', 'Asparagus', 'Lemon'],
      prepTime: 25,
    },
    {
      id: 'uw-s1',
      name: 'Greek Yogurt with Almonds',
      category: 'snack',
      calories: 350,
      protein: 22,
      carbs: 28,
      fat: 16,
      image: 'https://images.pexels.com/photos/128865/pexels-photo-128865.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['200g Greek yogurt', '40g almonds', '2 tbsp honey', 'Mixed berries'],
      prepTime: 5,
    },
  ],
  normal: [
    {
      id: 'nm-b1',
      name: 'Berry Granola Bowl',
      category: 'breakfast',
      calories: 380,
      protein: 14,
      carbs: 52,
      fat: 12,
      image: 'https://images.pexels.com/photos/128865/pexels-photo-128865.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['1 cup granola', '150g Greek yogurt', 'Mixed berries', '1 tbsp chia seeds'],
      prepTime: 5,
    },
    {
      id: 'nm-l1',
      name: 'Quinoa Veggie Power Bowl',
      category: 'lunch',
      calories: 450,
      protein: 18,
      carbs: 58,
      fat: 16,
      image: 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['1 cup quinoa', 'Roasted vegetables', 'Chickpeas', 'Tahini dressing', 'Spinach'],
      prepTime: 15,
    },
    {
      id: 'nm-d1',
      name: 'Grilled Chicken with Vegetables',
      category: 'dinner',
      calories: 420,
      protein: 35,
      carbs: 32,
      fat: 14,
      image: 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['180g chicken breast', 'Broccoli', 'Bell peppers', 'Olive oil', 'Brown rice'],
      prepTime: 20,
    },
    {
      id: 'nm-s1',
      name: 'Apple with Peanut Butter',
      category: 'snack',
      calories: 220,
      protein: 8,
      carbs: 28,
      fat: 10,
      image: 'https://images.pexels.com/photos/566564/pexels-photo-566564.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['1 apple', '2 tbsp peanut butter'],
      prepTime: 2,
    },
  ],
  overweight: [
    {
      id: 'ow-b1',
      name: 'Spinach Egg White Omelet',
      category: 'breakfast',
      calories: 220,
      protein: 20,
      carbs: 8,
      fat: 10,
      image: 'https://images.pexels.com/photos/566564/pexels-photo-566564.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['4 egg whites', 'Spinach', 'Cherry tomatoes', 'Feta cheese (1 tbsp)', 'Black pepper'],
      prepTime: 10,
    },
    {
      id: 'ow-l1',
      name: 'Grilled Chicken Salad',
      category: 'lunch',
      calories: 320,
      protein: 32,
      carbs: 18,
      fat: 12,
      image: 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['150g grilled chicken', 'Mixed greens', 'Cucumber', 'Cherry tomatoes', 'Balsamic vinaigrette'],
      prepTime: 15,
    },
    {
      id: 'ow-d1',
      name: 'Baked Cod with Steamed Broccoli',
      category: 'dinner',
      calories: 280,
      protein: 30,
      carbs: 14,
      fat: 8,
      image: 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['180g cod fillet', 'Broccoli', 'Lemon', 'Garlic', '1 tsp olive oil'],
      prepTime: 25,
    },
    {
      id: 'ow-s1',
      name: 'Carrot Sticks with Hummus',
      category: 'snack',
      calories: 150,
      protein: 6,
      carbs: 18,
      fat: 6,
      image: 'https://images.pexels.com/photos/128865/pexels-photo-128865.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['Carrot sticks', '3 tbsp hummus'],
      prepTime: 5,
    },
  ],
  obese: [
    {
      id: 'ob-b1',
      name: 'Vegetable Smoothie Bowl',
      category: 'breakfast',
      calories: 180,
      protein: 12,
      carbs: 22,
      fat: 5,
      image: 'https://images.pexels.com/photos/566564/pexels-photo-566564.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['Spinach', 'Cucumber', 'Green apple', 'Protein powder', 'Water'],
      prepTime: 5,
    },
    {
      id: 'ob-l1',
      name: 'Mixed Green Salad with Tuna',
      category: 'lunch',
      calories: 250,
      protein: 28,
      carbs: 12,
      fat: 8,
      image: 'https://images.pexels.com/photos/1640775/pexels-photo-1640775.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['120g tuna (water-packed)', 'Mixed greens', 'Cucumber', 'Red onion', 'Lemon juice'],
      prepTime: 10,
    },
    {
      id: 'ob-d1',
      name: 'Steamed Fish with Cauliflower',
      category: 'dinner',
      calories: 220,
      protein: 28,
      carbs: 10,
      fat: 6,
      image: 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['150g white fish', 'Cauliflower', 'Green beans', 'Lemon', 'Herbs'],
      prepTime: 20,
    },
    {
      id: 'ob-s1',
      name: 'Celery with Greek Yogurt Dip',
      category: 'snack',
      calories: 100,
      protein: 8,
      carbs: 8,
      fat: 3,
      image: 'https://images.pexels.com/photos/128865/pexels-photo-128865.jpeg?auto=compress&cs=tinysrgb&w=800',
      ingredients: ['Celery sticks', '100g plain Greek yogurt', 'Dill', 'Black pepper'],
      prepTime: 5,
    },
  ],
};

export function getMealsForCategory(category: BMICategory): Meal[] {
  return meals[category];
}

export function getMealTotals(meals: Meal[]) {
  return meals.reduce(
    (acc, m) => ({
      calories: acc.calories + m.calories,
      protein: acc.protein + m.protein,
      carbs: acc.carbs + m.carbs,
      fat: acc.fat + m.fat,
    }),
    { calories: 0, protein: 0, carbs: 0, fat: 0 }
  );
}
